---
- name: PostgreSQL | apt key
  tags:
  - apt
  apt_key:
    url: "{{ postgres_key }}"

- name: PostgreSQL | apt repo
  tags:
  - apt
  apt_repository:
    repo: "deb {{ postgres_repo }} {{ ansible_distribution_release }}-pgdg main"
    filename: postgresql

- name: PostgreSQL | packages
  tags:
  - package
  package:
    name: 
    - "postgresql-{{ postgresql_version }}"
    - "postgresql-client-{{ postgresql_version }}"
    - libpq-dev
    - python3-psycopg2

- name: PostgreSQL | config
  tags:
  - config
  template:
    src: "{{ item }}.j2"
    dest: "{{ postgresql_dir }}/{{ item }}"
    owner: "{{ postgresql_user }}"
    group: "{{ postgresql_user }}"
    mode: 0640
  loop:
  - pg_hba.conf
  - postgresql.conf
  notify: restart postgresql

- name: PostgreSQL | logrotate config
  tags:
  - logrotate
  copy:
    dest: /etc/logrotate.d/postgresql-common
    content: "/var/log/postgresql/*.log {\n  su postgres postgres \n}"

- name: PostgreSQL | backup cron
  tags:
  - cron
  cron:
    name: 'postgresql cron'
    cron_file: postgres
    minute: '18'
    hour: '3'
    user: "{{ postgresql_user }}"
    job: "/usr/bin/pg_dumpall -w | gzip -c --rsyncable > {{ postgresql_dump }}"

- name: PostgreSQL | service
  tags:
  - service
  service:
    name: postgresql
    state: started
    enabled: yes

