#! /usr/bin/env ansible-playbook
# Configure template role
# Replace 'db' with your own inventory group
---
- name: postgres | database
  hosts: db
  roles:
  - role: postgres
    tags:
    - postgres
    - db
